spring:
  application:
    name: aura-talk-back
  datasource:
    url: ${DB_LOCAL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        show_sql: ${SHOW_SQL}
        dialect: org.hibernate.dialect.MySQL8Dialect
  session:
    store-type: none

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_LOCAL_HOST}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-milliseconds: ${JWT_EXPIRATION}

server:
  port: ${SERVER_PORT}